### ISSUE TITLE
How do you execute these binaries?

### ISSUE THREAD

**Issue by RazCrimson** [UIM-SEC/ransomware-samples#1]
What target architecture are these binaries for?

I tried to execute them from a Ubuntu 20.04 VM. But I get a Exec format error.

Can anyone point me in the right direction to execute these?

**Comment by Programator2** [comment]
Most of them are x86 Windows binaries. Use [`file`](https://en.wikipedia.org/wiki/File_(command)) to identify the architecture. The only one for Linux is `lilocked`.

**Comment by RazCrimson** [comment]
Thanks for the reply.

**Comment by munirohitrishi** [comment]
can I get the binary of lilocked

**Comment by munirohitrishi** [comment]
exact  binary of lilocked
